<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRlvKFOe\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRlvKFOe/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRlvKFOe.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRlvKFOe\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRlvKFOe\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RlvKFOe',
    'container.build_id' => 'aa897be1',
    'container.build_time' => 1607090515,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRlvKFOe');
